### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by dfu5823** [MIPT-Oulu/MammogramAnnotationTool_public#1]
Hi, I am a medical student trying to use this tool for mammography image annotation of tumors. I tried following the instructions in the ReadMe -- I have all the required dependencies and I placed some DICOM images in the images folder as instructed but when I try to run the GUI the file selector does not allow me to select any .csv files. 

Based on these instructions: "Each examination is required to have 4 standard mammographic views. These examinations should be listed in a dedicated study_info.csv file, an example file is provided. The study_info.csv file should be located within the root of your CUSTOMDATASET folder. Mammograms should be located in images within the same root folder. The software will make additional subfolders for saving annotation masks and other results in mat and csv format."

"You can open a set of studies to be annotated by navigating to the main graphical user interface window drop down menu 'File' and choosing 'Open'. From the following dialog you then choose a CSV file containing the StudyInstanceUID's corresponding to the mammogram image locations (folders on your hard drive)."

To be specific about what I did -- I put four dicom files for one patient in a folder and placed two of those patient folders in the images folder. However, when I tried using the Open dialog to select a CSV file the dialog did not allow me to select any csv files.

Here are two images that show where I am getting stuck with the file selector. Could you help me figure out what the issue is here and how to set up my csv files properly so that I can open up my dicom files and being annotating?

<img width="612" alt="Screenshot 2023-01-22 at 6 50 59 PM" src="https://user-images.githubusercontent.com/71274065/213947141-7f39c666-7e8c-45aa-99ae-4c27f39cfb7c.png">
<img width="617" alt="Screenshot 2023-01-22 at 6 51 38 PM" src="https://user-images.githubusercontent.com/71274065/213947164-edfef35e-54f4-4d8a-8c21-d4e6fa342d00.png">

Please contact me at danfu42@gmail.com if you need any more information.

**Comment by aisosalo** [comment]
Greetings! Sorry for the late reply. Looks like you have done everything correctly. I could not reproduce this error in a Windows environment. Linux installation I did not have at hand. There are reported issues with MATLAB and the native file chooser in MacOS Catalina (10.15.1). Since you have full access to the source code I am sure you already figured out how to directly access a certain CSV file.
